### ISSUE TITLE
Taking this further with a RCL and web app?

### ISSUE THREAD

**Issue by stap123** [chrissainty/ondotnet-tailwindcss#2]
Hi Chris,

Just watched your on dot net video on YouTube. Looks great 👍 

It got me thinking about taking it a step further but I have no idea how to do it so thought I'd ask here and see if someone had a clue.

Would it be possible to create a razor class library (RCL) that contains your Blazor components. You could then put tailwind in using the scripts as you have in this sample. The RCL would have a pruned version of tailwind.

Imagine then that you add a reference to this RCL via a NuGet package to a Blazor (web assembly) project that you also want to use tailwind in. You can obviously set up the same scripts to prune the tailwind css inside that web app but that would result in 2 css files that likely contain many duplicated styles for your app.

Do you think there would be a way to automatically take the pruned css from the RCL and combine it with the one in the web app so that you end up with a single css file that contains the pruned version for what you need in the web app and what the RCL needs? (This would work if you copied the css out of the RCL and manually included as in input somewhere in your web app but every time the NuGet updated you'd have to go get the new css file)

Does that make any sense at all? 🤷

**Comment by chrissainty** [comment]
I don't think this can work as Tailwind needs to scan the razor and HTML files to understand what classes you're using. There won't be any files for it to scan for the RCL as they will be in a NuGet package.

I guess this issue is no different to using a library which might use Bootstrap in an app which uses Bootstrap.

**Comment by stap123** [comment]
> I don't think this can work as Tailwind needs to scan the razor and HTML files to understand what classes you're using. There won't be any files for it to scan for the RCL as they will be in a NuGet package.
> 
> I guess this issue is no different to using a library which might use Bootstrap in an app which uses Bootstrap.

Yeah I wasn't sure if you could access the compiled CSS from inside the NuGet package and tell Tailwind that it was another source that should be scanned 😃 

It just seems like a waste to make users download the same CSS styles twice especially with something like Tailwind where the classes only do one thing so are *almost* guaranteed to be the exact same code.
